Мясо гондолы для трейторов поваров
MassMeta/tgstation pull request #4
Opened 2023-02-28 18:26 UTC by SuperSlayer0

## About The Pull Request

Позволяет трейторам поварам купить мясо гондолы(содержит реагент, заражающий людей вирусом, который через некоторое время превращает их в гондол, вирус можно вылечить) за 6 ТК

## Why It's Good For The Game

Смешной трейторский предмет с возможностью для гиммиков

## Changelog

:cl:
add: Позволяет трейторам поварам покупать мясо гондолы
/:cl:

2023-02-28 23:22 UTC, Huz2e requested changes

2023-02-28 23:22 UTC, Huz2e commented on code/modules/uplink/uplink_items/job.dm
> +	cost = 6
Цену сильно повысить надо, либо вся станция гондолами будет.

2023-03-01 05:32 UTC, SuperSlayer0 commented on code/modules/uplink/uplink_items/job.dm
> +	cost = 6
До скольки?

2023-03-01 06:22 UTC, Huz2e commented on code/modules/uplink/uplink_items/job.dm
> +	cost = 6
До 10, хотя бы.

2023-03-01 07:10 UTC, SuperSlayer0 commented on code/modules/uplink/uplink_items/job.dm
> +	cost = 6
Сделанно

2023-03-01 07:14 UTC, merged